#
# MotionEstimation
#
# Required variables:
#  - MAXCOMPILER_SIM_CENTOS6_IMAGE: image from Centos 6 with MaxCompiler and MaxCompiler Simulator
#  - MAXCOMPILER_SIM_CENTOS7_IMAGE: image from Centos 7 with MaxCompiler and MaxCompiler Simulator
#  - MAXCOMPILER_ISE_CENTOS6_IMAGE: image from Centos 6 with MaxCompiler and Xilinx ISE
#  - MAXCOMPILER_QUARTUS_CENTOS6_IMAGE: image from Centos 6 with MaxCompiler and Quartus II
#

stages:
- make-sim
- run-sim
- make-dfe
- make-test-dfe
- run-dfe

##
# This template is used for building app for all DFE RunRules.
# sed is used in order to fail build if all cost tables fail to meet timing
# Required variables:
#  - RUNRULE - RunRule for which we want to build app
#  - TARGET - target for make file (build, build_test, runsim or runsim_test)
#
.make-template: &make-definition
  script:
    - sed -i s/failonerror=\"false\"/failonerror=\"true\"/g APP/RunRules/$RUNRULE/ME.xml
    - make -C APP/CPUCode RUNRULE=$RUNRULE $TARGET
  artifacts:
    expire_in: 30 days
    paths:
      - APP/RunRules/$RUNRULE/maxfiles/*.max
      - APP/RunRules/$RUNRULE/maxfiles/*.h
      - APP/RunRules/$RUNRULE/include/*.h
      - APP/RunRules/$RUNRULE/binaries

##
# This template is used for running of an app for all DFE RunRules.
# Required variables:
#  - RUNRULE - RunRule for which we want to build app
#  - TEST    - if this variable is set run test
#
.run-template:
  script: &run-script
    - APP/RunRules/$RUNRULE/binaries/`[ -n "$TEST" ] && echo me_test || echo motionEstimation 11 9`

##
# In the following section some jobs are hidden because
# the test or corresponding run rule hasn't been made yet
# or particular dfe is not available to be run from ci job
#

# Simulation
make-sim-MotionEstimation:
  image: $MAXCOMPILER_SIM_CENTOS6_IMAGE
  variables:
    RUNRULE: Simulation
    TARGET: build
  stage: make-sim
  tags:
    - maxcompiler-sim
  <<: *make-definition

run-sim-MotionEstimation:
  image: $MAXCOMPILER_SIM_CENTOS6_IMAGE
  variables:
    RUNRULE: Simulation
    TARGET: runsim
  stage: run-sim
  tags:
    - maxcompiler-sim
  <<: *make-definition

.make-test-sim-MotionEstimation:
  image: $MAXCOMPILER_SIM_CENTOS7_IMAGE
  variables:
    RUNRULE: Simulation
    TARGET: build_test
  stage: make-sim
  tags:
    - maxcompiler-sim
  <<: *make-definition

.run-test-sim-MotionEstimation:
  image: $MAXCOMPILER_SIM_CENTOS7_IMAGE
  variables:
    RUNRULE: Simulation
    TARGET: runsim_test
  stage: run-sim
  tags:
    - maxcompiler-sim
  <<: *make-definition

# DFE builds and tests
# Galava
make-Galava-MotionEstimation:
  image: $MAXCOMPILER_QUARTUS_CENTOS6_IMAGE
  variables:
    RUNRULE: Galava
    TARGET: build
  stage: make-dfe
  tags:
    - maxcompiler-dfe
  <<: *make-definition

.make-Galava-test-MotionEstimation:
  image: $MAXCOMPILER_SIM_CENTOS7_IMAGE
  variables:
    RUNRULE: Galava
    TARGET: build_test
  stage: make-test-dfe
  tags:
    - maxcompiler-sim
  dependencies:
    - make-Galava-MotionEstimation
  <<: *make-definition

run-Galava-MotionEstimation:
  variables:
    RUNRULE: Galava
  script: *run-script
  stage: run-dfe
  tags:
    - galava
    - centos6
  dependencies:
    - make-Galava-MotionEstimation

.run-Galava-test-MotionEstimation:
  variables:
    RUNRULE: Galava
    TEST: exists
  script: *run-script
  stage: run-dfe
  tags:
    - galava
    - centos7
  dependencies:
    - make-Galava-test-MotionEstimation

# Maia
make-Maia-MotionEstimation:
  image: $MAXCOMPILER_QUARTUS_CENTOS6_IMAGE
  variables:
    RUNRULE: Maia
    TARGET: build
  stage: make-dfe
  tags:
    - maxcompiler-dfe
  <<: *make-definition

.make-Maia-test-MotionEstimation:
  image: $MAXCOMPILER_SIM_CENTOS7_IMAGE
  variables:
    RUNRULE: Maia
    TARGET: build_test
  stage: make-test-dfe
  tags:
    - maxcompiler-sim
  dependencies:
    - make-Maia-MotionEstimation
  <<: *make-definition

run-Maia-MotionEstimation:
  variables:
    RUNRULE: Maia
  script: *run-script
  stage: run-dfe
  tags:
    - maia
    - centos6
  dependencies:
    - make-Maia-MotionEstimation

.run-Maia-test-MotionEstimation:
  variables:
    RUNRULE: Maia
    TEST: exists
  script: *run-script
  stage: run-dfe
  tags:
    - maia
    - centos7
  dependencies:
    - make-Maia-test-MotionEstimation

# Isca
make-Isca-MotionEstimation:
  image: $MAXCOMPILER_QUARTUS_CENTOS6_IMAGE
  variables:
    RUNRULE: Isca
    TARGET: build
  stage: make-dfe
  tags:
    - maxcompiler-dfe
  <<: *make-definition

.make-Isca-test-MotionEstimation:
  image: $MAXCOMPILER_SIM_CENTOS7_IMAGE
  variables:
    RUNRULE: Isca
    TARGET: build_test
  stage: make-test-dfe
  tags:
    - maxcompiler-sim
  dependencies:
    - make-Isca-MotionEstimation
  <<: *make-definition

.run-Isca-MotionEstimation:
  variables:
    RUNRULE: Isca
  script: *run-script
  stage: run-dfe
  tags:
    - isca
    - centos6
  dependencies:
    - make-Isca-MotionEstimation

.run-Isca-test-MotionEstimation:
  variables:
    RUNRULE: Isca
    TEST: exists
  script: *run-script
  stage: run-dfe
  tags:
    - isca
    - centos7
  dependencies:
    - make-Isca-test-MotionEstimation

# Vectis
make-Vectis-MotionEstimation:
  image: $MAXCOMPILER_ISE_CENTOS6_IMAGE
  variables:
    RUNRULE: Vectis
    TARGET: build
  stage: make-dfe
  tags:
    - maxcompiler-dfe
  <<: *make-definition

.make-Vectis-test-MotionEstimation:
  image: $MAXCOMPILER_SIM_CENTOS7_IMAGE
  variables:
    RUNRULE: Vectis
    TARGET: build_test
  stage: make-test-dfe
  tags:
    - maxcompiler-sim
  dependencies:
    - make-Vectis-MotionEstimation
  <<: *make-definition

run-Vectis-MotionEstimation:
  variables:
    RUNRULE: Vectis
  script: *run-script
  stage: run-dfe
  tags:
    - vectis
    - centos6
  dependencies:
    - make-Vectis-MotionEstimation

.run-Vectis-test-MotionEstimation:
  variables:
    RUNRULE: Vectis
    TEST: exists
  script: *run-script
  stage: run-dfe
  tags:
    - vectis
    - centos7
  dependencies:
    - make-Vectis-test-MotionEstimation

# Coria
make-Coria-MotionEstimation:
  image: $MAXCOMPILER_QUARTUS_CENTOS6_IMAGE
  variables:
    RUNRULE: Coria
    TARGET: build
  stage: make-dfe
  tags:
    - maxcompiler-dfe
  <<: *make-definition

.make-Coria-test-MotionEstimation:
  image: $MAXCOMPILER_SIM_CENTOS7_IMAGE
  variables:
    RUNRULE: Coria
    TARGET: build_test
  stage: make-test-dfe
  tags:
    - maxcompiler-sim
  dependencies:
    - make-Coria-MotionEstimation
  <<: *make-definition

.run-Coria-MotionEstimation:
  variables:
    RUNRULE: Coria
  script: *run-script
  stage: run-dfe
  tags:
    - coria
    - centos6
  dependencies:
    - make-Coria-MotionEstimation

.run-Coria-test-MotionEstimation:
  variables:
    RUNRULE: Coria
    TEST: exists
  script: *run-script
  stage: run-dfe
  tags:
    - coria
    - centos7
  dependencies:
    - make-Coria-test-MotionEstimation
