#
# MotionEstimation
#
# Required variables:
#  - MAXCOMPILER_SIM_CENTOS6_IMAGE: image from Centos 6 with MaxCompiler and MaxCompiler Simulator
#  - MAXCOMPILER_SIM_CENTOS7_IMAGE: image from Centos 7 with MaxCompiler and MaxCompiler Simulator
#  - MAXCOMPILER_ISE_CENTOS6_IMAGE: image from Centos 6 with MaxCompiler and Xilinx ISE
#  - MAXCOMPILER_QUARTUS_CENTOS6_IMAGE: image from Centos 6 with MaxCompiler and Quartus II
#

stages:
- make-sim
- run-sim
- make-dfe
- make-test-dfe
- run-dfe

##
#  This template is used for building app for all DFE RunRules.
#  sed is used in order to fail build if all cost tables fail to meet timing
#  Required variables:
#  - RUNRULE - RunRule for which we want to build app
#  - TARGET - target for make file (build, build_test, runsim or runsim_test)
#
.make-template:
  script: &make-script
    - sed -i s/failonerror=\"false\"/failonerror=\"true\"/g APP/RunRules/$RUNRULE/ME.xml
    - make -C APP/CPUCode RUNRULE=$RUNRULE $TARGET
##
#  This template is used for running of an app for all DFE RunRules.
#  Required variables:
#  - RUNRULE - RunRule for which we want to build app
#  - TEST    - if this variable is set run test
#
.run-template:
  script: &run-script
    - APP/RunRules/$RUNRULE/binaries/`[ -n "$TEST" ] && echo me_test || echo motionEstimation 11 9`

##
#
#
#
#
#
.make-MotionEstimation-template: &make-MotionEstimation-definition
  image: $IMAGE
  script: *make-script
  stage: make-dfe
  tags:
    - maxcompiler-dfe
  artifacts:
    paths:
      - APP/RunRules/$RUNRULE/maxfiles/*.max
      - APP/RunRules/$RUNRULE/maxfiles/*.h
      - APP/RunRules/$RUNRULE/include/*.h
      - APP/RunRules/$RUNRULE/binaries

##
#
#
#
#
#
.make-test-MotionEstimation-template: &make-test-MotionEstimation-definition
  image: $IMAGE
  script: *make-script
  stage: make-test-dfe
  tags:
    - maxcompiler-sim
  artifacts:
    paths:
      - APP/RunRules/$RUNRULE/binaries

##
#
#
#
#
#
.run-MotionEstimation-template: &run-MotionEstimation-definition
  script: *run-script
  stage: run-dfe
  tags:
    - $(echo $RUNRULE | tr '[:upper:]' '[:lower:]')
    - centos6

##
#
#
#
#
#
.run-test-MotionEstimation-template: &run-test-MotionEstimation-definition
  script: *run-script
  stage: run-dfe
  tags:
    - $(echo $RUNRULE | tr '[:upper:]' '[:lower:]')
    - centos7

# Simulation
make-sim-MotionEstimation:
  image: $MAXCOMPILER_SIM_CENTOS6_IMAGE
  variables:
    RUNRULE: Simulation
    TARGET: build
  script: *make-script
  stage: make-sim
  tags:
    - maxcompiler-sim

run-sim-MotionEstimation:
  image: $MAXCOMPILER_SIM_CENTOS6_IMAGE
  variables:
    RUNRULE: Simulation
    TARGET: runsim
  script: *make-script
  stage: run-sim
  tags:
    - maxcompiler-sim

.make-test-sim-MotionEstimation:
  image: $MAXCOMPILER_SIM_CENTOS7_IMAGE
  variables:
    RUNRULE: Simulation
    TARGET: build_test
  script: *make-script
  stage: make-sim
  tags:
    - maxcompiler-sim

.run-test-sim-MotionEstimation:
  image: $MAXCOMPILER_SIM_CENTOS7_IMAGE
  variables:
    RUNRULE: Simulation
    TARGET: runsim_test
  script: *make-script
  stage: run-sim
  tags:
    - maxcompiler-sim

# DFE builds and tests
# Galava
make-Galava-MotionEstimation:
  variables:
    IMAGE: $MAXCOMPILER_QUARTUS_CENTOS6_IMAGE
    RUNRULE: Galava
    TARGET: build
  <<: *make-MotionEstimation-definition

.make-Galava-test-MotionEstimation:
  variables:
    IMAGE: $MAXCOMPILER_SIM_CENTOS7_IMAGE
    RUNRULE: Galava
    TARGET: build_test
  <<: *make-test-MotionEstimation-definition
  dependencies:
    - make-Galava-MotionEstimation

run-Galava-MotionEstimation:
  variables:
    RUNRULE: Galava
  <<: *run-MotionEstimation-definition
  dependencies:
    - make-Galava-MotionEstimation

.run-Galava-test-MotionEstimation:
  variables:
    RUNRULE: Galava
    TEST: exists
  <<: *run-test-MotionEstimation-definition
  dependencies:
    - make-Galava-test-MotionEstimation

# Maia
make-Maia-MotionEstimation:
  variables:
    IMAGE: $MAXCOMPILER_QUARTUS_CENTOS6_IMAGE
    RUNRULE: Maia
    TARGET: build
  <<: *make-MotionEstimation-definition

.make-Maia-test-MotionEstimation:
  variables:
    IMAGE: $MAXCOMPILER_SIM_CENTOS7_IMAGE
    RUNRULE: Maia
    TARGET: build_test
  <<: *make-test-MotionEstimation-definition
  dependencies:
    - make-Maia-MotionEstimation

run-Maia-MotionEstimation:
  variables:
    RUNRULE: Maia
  <<: *run-MotionEstimation-definition
  dependencies:
    - make-Maia-MotionEstimation

.run-Maia-test-MotionEstimation:
  variables:
    RUNRULE: Maia
    TEST: exists
  <<: *run-test-MotionEstimation-definition
  dependencies:
    - make-Maia-test-MotionEstimation

# Isca
make-Isca-MotionEstimation:
  variables:
    IMAGE: $MAXCOMPILER_QUARTUS_CENTOS6_IMAGE
    RUNRULE: Isca
    TARGET: build
  <<: *make-MotionEstimation-definition

.make-Isca-test-MotionEstimation:
  variables:
    IMAGE: $MAXCOMPILER_SIM_CENTOS7_IMAGE
    RUNRULE: Isca
    TARGET: build_test
  <<: *make-test-MotionEstimation-definition
  dependencies:
    - make-Isca-MotionEstimation

.run-Isca-MotionEstimation:
# Can not be run via ci job yet because Isca is in not available to be run from ci job
  variables:
    RUNRULE: Isca
  <<: *run-MotionEstimation-definition
  dependencies:
    - make-Isca-MotionEstimation

.run-Isca-test-MotionEstimation:
# Can not be run via ci job yet because Isca is in not available to be run from ci job
  variables:
    RUNRULE: Isca
    TEST: exists
  <<: *run-test-MotionEstimation-definition
  dependencies:
    - make-Isca-test-MotionEstimation

# Vectis
.make-Vectis-MotionEstimation:
  variables:
    IMAGE: $MAXCOMPILER_ISE_CENTOS6_IMAGE
    RUNRULE: Vectis
    TARGET: build
  <<: *make-MotionEstimation-definition

.make-Vectis-test-MotionEstimation:
  variables:
    IMAGE: $MAXCOMPILER_SIM_CENTOS7_IMAGE
    RUNRULE: Vectis
    TARGET: build_test
  <<: *make-test-MotionEstimation-definition
  dependencies:
    - make-Vectis-MotionEstimation

.run-Vectis-MotionEstimation:
  variables:
    RUNRULE: Vectis
  <<: *run-MotionEstimation-definition
  dependencies:
    - make-Vectis-MotionEstimation

.run-Vectis-test-MotionEstimation:
  variables:
    RUNRULE: Vectis
    TEST: exists
  <<: *run-test-MotionEstimation-definition
  dependencies:
    - make-Vectis-test-MotionEstimation

# Coria
make-Coria-MotionEstimation:
  variables:
    IMAGE: $MAXCOMPILER_QUARTUS_CENTOS6_IMAGE
    RUNRULE: Coria
    TARGET: build
  <<: *make-MotionEstimation-definition

.make-Coria-test-MotionEstimation:
  variables:
    IMAGE: $MAXCOMPILER_SIM_CENTOS7_IMAGE
    RUNRULE: Coria
    TARGET: build_test
  <<: *make-test-MotionEstimation-definition
  dependencies:
    - make-Coria-MotionEstimation

.run-Coria-MotionEstimation:
  variables:
    RUNRULE: Coria
  <<: *run-MotionEstimation-definition
  dependencies:
    - make-Coria-MotionEstimation

.run-Coria-test-MotionEstimation:
  variables:
    RUNRULE: Coria
    TEST: exists
  <<: *run-test-MotionEstimation-definition
  dependencies:
    - make-Coria-test-MotionEstimation
